apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: strimx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strimx-web
  template:
    metadata:
      labels:
        app: strimx-web
    spec:
      containers:
      - name: php-web
        image: nagoorvali10/strimx-app:latest # <--- CHANGED to your likely username
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "1234"
        - name: DB_NAME
          value: "strimx_db"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: strimx-ns
spec:
  selector:
    app: strimx-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  type: NodePort